apiVersion: v1
kind: Secret
metadata:
  name: mail-secret
type: Opaque
stringData:
  SPRING_MAIL_HOST: smtp.gmail.com
  SPRING_MAIL_PORT: "587"
  SPRING_MAIL_USERNAME: tvoje_email@gmail.com
  SPRING_MAIL_PASSWORD: tvoje_heslo
  SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: "true"
  SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: "true"