# FILE: base/insurance-app/db-service.yaml

apiVersion: v1
kind: Service
metadata:
  name: mariadb-service # Názov Service MUSÍ zodpovedať DATABASE_HOST v deployment.yaml
  labels:
    app: mariadb
spec:
  # Headless Service je odporúčaný pre StatefulSets,
  # ale pre jednoduchú inštaláciu MariaDB postačuje ClusterIP.
  type: ClusterIP 
  
  # Definuje, na ktoré Pody Service smeruje (podľa app: mariadb label zo StatefulSetu)
  selector:
    app: mariadb
  
  # Mapovanie portov
  ports:
    - protocol: TCP
      port: 3306         # Štandardný MariaDB port
      targetPort: 3306   # Port MariaDB kontajnera
      name: mariadb
