apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - db-service.yaml
  - mariadb-statefulset.yaml
  - secrets/mariadb-secret.yaml
  - secrets/mail-secret.yaml
  
configMapGenerator:
  - name: mariadb-init-scripts
    files:
      - db-init-scripts/init.sql  
