# FILE: base/insurance-app/mariadb-statefulset.yaml

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb-insurance-app
  labels:
    app: mariadb
    tier: database
spec:
  serviceName: mariadb-service # Musí zodpovedať Service (db-service.yaml)
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
        tier: database
    spec:
      containers:
      - name: mariadb-container
        image: mariadb:10.11 # Stabilná verzia pre produkciu
        ports:
        - containerPort: 3306
          name: mariadb
        
        volumeMounts:
        - name: mariadb-volume
          mountPath: /var/lib/mysql 
        
        # --- Environment Variables pre MariaDB ---
        env:
        # Používa Secret, ktorý ešte len definujeme!
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: mariadb-root-password 
        - name: MARIADB_USER
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: mariadb-user
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mariadb-secret
              key: mariadb-password
        - name: MARIADB_DATABASE
          value: insurance_db
        
        # --- Limity na VM ---
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
            
  # --- Definícia Perzistentného Úložiska (Persistent Volume Claim) ---
  volumeClaimTemplates:
  - metadata:
      name: mariadb-volume
    spec:
      accessModes: [ "ReadWriteOnce" ] 
      # Zvoľte triedu úložiska pre K3s/Minikube. Ak používate K3s, 'local-path' je default.
      # Použijeme 'standard', čo je bežný placeholder.
      storageClassName: "local-path" 
      resources:
        requests:
          storage: 5Gi
